# -*- coding: utf-8 -*-
"""bleeding_assessment_tool

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyImiLX2gFUrAnSAlzdEFm6mNK27Bbg_
"""

import streamlit as st

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Bleeding Assessment Tool",
    page_icon="🩸",
    layout="centered",
    initial_sidebar_state="collapsed",
)

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=DM+Sans:wght@300;400;500&display=swap');

:root {
    --primary: #0d6efd;
    --danger:  #dc3545;
    --success: #198754;
    --warning: #fd7e14;
    --teal:    #0dcaf0;
    --bg:      #f0f4f8;
    --card:    #ffffff;
    --text:    #1a1a2e;
    --muted:   #6c757d;
}

html, body, [class*="css"] {
    font-family: 'DM Sans', sans-serif;
    background-color: var(--bg);
    color: var(--text);
}

h1, h2, h3 {
    font-family: 'Playfair Display', serif;
}

/* Progress bar */
.stProgress > div > div > div {
    background: linear-gradient(90deg, #0d6efd, #0dcaf0);
    border-radius: 10px;
}
.stProgress > div > div {
    background: #dee2e6;
    border-radius: 10px;
}

/* Buttons */
div.stButton > button {
    border-radius: 50px;
    padding: 0.55rem 2rem;
    font-weight: 500;
    font-size: 1rem;
    border: none;
    transition: transform 0.15s, box-shadow 0.15s;
}
div.stButton > button:hover {
    transform: translateY(-2px);
    box-shadow: 0 6px 20px rgba(0,0,0,0.12);
}

/* Cards */
.bat-card {
    background: var(--card);
    border-radius: 18px;
    padding: 2.5rem 2rem;
    box-shadow: 0 4px 24px rgba(0,0,0,0.07);
    margin-bottom: 1.5rem;
}

.q-number {
    font-size: 0.85rem;
    font-weight: 500;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #0d6efd;
    margin-bottom: 0.4rem;
}

.q-text {
    font-family: 'Playfair Display', serif;
    font-size: 1.5rem;
    line-height: 1.4;
    color: var(--text);
    margin-bottom: 0.5rem;
}

.q-hint {
    font-size: 0.88rem;
    color: var(--muted);
    margin-bottom: 1.5rem;
}

/* Result badge */
.result-badge {
    display: inline-block;
    border-radius: 50px;
    padding: 0.5rem 1.4rem;
    font-weight: 600;
    font-size: 1.05rem;
    margin-bottom: 1rem;
}

.score-circle {
    width: 120px;
    height: 120px;
    border-radius: 50%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    margin: 0 auto 1.5rem;
    font-family: 'Playfair Display', serif;
}

.score-num {
    font-size: 2.2rem;
    font-weight: 700;
    line-height: 1;
}
.score-denom {
    font-size: 0.9rem;
    opacity: 0.75;
}

.result-row {
    display: flex;
    align-items: center;
    gap: 0.6rem;
    padding: 0.55rem 0;
    border-bottom: 1px solid #f0f0f0;
    font-size: 0.95rem;
}

.dot-yes { color: #dc3545; font-size: 1.1rem; }
.dot-no  { color: #198754; font-size: 1.1rem; }

.disclaimer {
    background: #fff3cd;
    border-left: 4px solid #fd7e14;
    border-radius: 0 10px 10px 0;
    padding: 0.9rem 1.1rem;
    font-size: 0.85rem;
    color: #7d4e00;
    margin-top: 1.5rem;
}
</style>
""", unsafe_allow_html=True)

# ── Questions ─────────────────────────────────────────────────────────────────
QUESTIONS = [
    {
        "id": 1,
        "text": "Do you bruise easily without a clear cause, forming bruises larger than a 50-paise coin?",
        "hint": "Spontaneous bruising not related to trauma",
        "category": "Bruising",
        "weight": 1,
    },
    {
        "id": 2,
        "text": "Have you ever had nosebleeds (epistaxis) lasting more than 10 minutes or requiring medical attention?",
        "hint": "Includes spontaneous and recurrent nosebleeds",
        "category": "Epistaxis",
        "weight": 1,
    },
    {
        "id": 3,
        "text": "Do your gums bleed spontaneously or during routine toothbrushing?",
        "hint": "Oral cavity / gum bleeding",
        "category": "Oral Cavity",
        "weight": 1,
    },
    {
        "id": 4,
        "text": "Have you ever bled excessively after a tooth extraction or dental procedure?",
        "hint": "Bleeding requiring additional intervention after dental work",
        "category": "Post-Dental Bleeding",
        "weight": 1,
    },
    {
        "id": 5,
        "text": "Have you ever had prolonged or heavy bleeding after a surgical procedure?",
        "hint": "Bleeding beyond what was expected post-operatively",
        "category": "Post-Surgical Bleeding",
        "weight": 1,
    },
    {
        "id": 6,
        "text": "Have you ever required a blood transfusion due to a bleeding episode?",
        "hint": "Any transfusion related to bleeding, not surgery itself",
        "category": "Transfusion Requirement",
        "weight": 2,
    },
    {
        "id": 7,
        "text": "Do you experience heavy menstrual bleeding (periods lasting >7 days or soaking a pad/tampon every hour)?",
        "hint": "For female patients; skip if not applicable",
        "category": "Menorrhagia",
        "weight": 1,
    },
    {
        "id": 8,
        "text": "Have you ever been hospitalised or had an emergency visit specifically because of bleeding?",
        "hint": "Excludes planned surgical admissions",
        "category": "Emergency/Hospitalisation",
        "weight": 2,
    },
    {
        "id": 9,
        "text": "Have you ever had bleeding into a joint (haemarthrosis), causing pain and swelling?",
        "hint": "Typically knees, elbows, or ankles",
        "category": "Haemarthrosis",
        "weight": 2,
    },
    {
        "id": 10,
        "text": "Have you ever had a muscle haematoma (deep bruise / bleed inside a muscle)?",
        "hint": "Often without significant trauma",
        "category": "Muscle Haematoma",
        "weight": 2,
    },
    {
        "id": 11,
        "text": "Have you ever noticed blood in your urine (haematuria) without a urinary infection?",
        "hint": "Frank or microscopic haematuria not explained by infection",
        "category": "Haematuria",
        "weight": 1,
    },
    {
        "id": 12,
        "text": "Have you ever had blood in your stools or a gastrointestinal bleed?",
        "hint": "Melaena, haematochezia, or confirmed GI bleeding",
        "category": "GI Bleeding",
        "weight": 1,
    },
    {
        "id": 13,
        "text": "Has a close family member (parent, sibling, child) been diagnosed with a bleeding disorder?",
        "hint": "E.g. haemophilia, von Willebrand disease, platelet disorder",
        "category": "Family History",
        "weight": 1,
    },
    {
        "id": 14,
        "text": "Have you ever had excessive bleeding after childbirth (postpartum haemorrhage ≥500 mL)?",
        "hint": "For female patients who have delivered; skip if not applicable",
        "category": "Postpartum Haemorrhage",
        "weight": 1,
    },
    {
        "id": 15,
        "text": "Do minor cuts or wounds take unusually long to stop bleeding (>15 minutes of direct pressure)?",
        "hint": "Bleeding from minor wounds",
        "category": "Wound Bleeding",
        "weight": 1,
    },
    {
        "id": 16,
        "text": "Have you ever had a spontaneous intracranial bleed or been told you had bleeding in/around the brain?",
        "hint": "ICH, subdural or subarachnoid haemorrhage not related to trauma",
        "category": "Intracranial Bleeding",
        "weight": 3,
    },
    {
        "id": 17,
        "text": "Have you been treated with iron supplements or been diagnosed with iron-deficiency anaemia due to bleeding?",
        "hint": "Anaemia attributed to chronic blood loss",
        "category": "Anaemia / Iron Deficiency",
        "weight": 1,
    },
    {
        "id": 18,
        "text": "Do you develop small red/purple pin-point spots on the skin (petechiae) without injury?",
        "hint": "Petechiae especially on lower limbs or mucous membranes",
        "category": "Petechiae",
        "weight": 1,
    },
    {
        "id": 19,
        "text": "Do you bleed excessively when taking aspirin, NSAIDs, or blood-thinning medications?",
        "hint": "Disproportionate bleeding on antiplatelet / anticoagulant drugs",
        "category": "Drug-Enhanced Bleeding",
        "weight": 1,
    },
    {
        "id": 20,
        "text": "Have you ever had a miscarriage or pregnancy loss associated with heavy bleeding?",
        "hint": "For female patients; skip if not applicable",
        "category": "Pregnancy-Related Bleeding",
        "weight": 1,
    },
]

# ── Category classification ───────────────────────────────────────────────────
def classify(score, weighted_score):
    if weighted_score == 0:
        return ("Low Risk", "#198754", "✅",
                "Your responses suggest a low likelihood of a significant bleeding disorder. "
                "Routine follow-up with your physician is recommended.")
    elif weighted_score <= 3:
        return ("Borderline / Mild", "#fd7e14", "⚠️",
                "There are some bleeding symptoms present. A clinical evaluation and basic "
                "haematology workup (CBC, PT, aPTT) is advisable. Consider discussing with a haematologist.")
    elif weighted_score <= 6:
        return ("Moderate Risk", "#dc3545", "🔴",
                "Multiple bleeding symptoms are present. Referral to a haematologist is recommended "
                "for further evaluation including von Willebrand factor assays and platelet function tests.")
    else:
        return ("High Risk — Urgent Evaluation", "#6f42c1", "🚨",
                "Significant bleeding symptoms across multiple domains. Urgent haematology referral is "
                "strongly advised. Comprehensive bleeding disorder workup including factor assays, "
                "platelet aggregation studies, and fibrinogen levels should be performed.")

# ── Session state init ────────────────────────────────────────────────────────
if "page" not in st.session_state:
    st.session_state.page = 0          # 0 = intro, 1-20 = questions, 21 = results
if "answers" not in st.session_state:
    st.session_state.answers = {}

# ── Helper ────────────────────────────────────────────────────────────────────
def go_to(page):
    st.session_state.page = page

# ══════════════════════════════════════════════════════════════════════════════
# INTRO PAGE
# ══════════════════════════════════════════════════════════════════════════════
if st.session_state.page == 0:
    st.markdown("""
    <div style='text-align:center; padding: 2rem 0 1rem;'>
        <div style='font-size:3.5rem;'>🩸</div>
        <h1 style='font-size:2.5rem; margin:0.3rem 0;'>Bleeding Assessment Tool</h1>
        <p style='color:#6c757d; font-size:1.05rem; max-width:520px; margin: 0.5rem auto 1.5rem;'>
            A structured 20-question clinical screening instrument based on the ISTH BAT framework
            to assess the likelihood of an underlying bleeding disorder.
        </p>
    </div>
    """, unsafe_allow_html=True)

    col1, col2, col3 = st.columns([1, 4, 1])
    with col2:
        st.markdown("""
        <div class='bat-card'>
            <b>📋 Instructions</b><br><br>
            Answer each question with <b>Yes</b> or <b>No</b> based on your personal history.<br><br>
            • 20 questions covering key bleeding domains<br>
            • Takes approximately <b>3–5 minutes</b><br>
            • Results are <b>for screening purposes only</b> and do not replace clinical evaluation
        </div>
        """, unsafe_allow_html=True)

        if st.button("▶  Start Assessment", use_container_width=True, type="primary"):
            st.session_state.answers = {}
            go_to(1)
            st.rerun()

# ══════════════════════════════════════════════════════════════════════════════
# QUESTION PAGES  (1-20)
# ══════════════════════════════════════════════════════════════════════════════
elif 1 <= st.session_state.page <= 20:
    q_idx = st.session_state.page - 1
    q = QUESTIONS[q_idx]
    total = len(QUESTIONS)

    # Progress
    st.progress(q_idx / total)
    st.markdown(f"<p style='text-align:right; color:#6c757d; font-size:0.85rem;'>Question {q_idx+1} of {total}</p>",
                unsafe_allow_html=True)

    col1, col2, col3 = st.columns([1, 5, 1])
    with col2:
        st.markdown(f"""
        <div class='bat-card'>
            <div class='q-number'>Question {q['id']} &nbsp;·&nbsp; {q['category']}</div>
            <div class='q-text'>{q['text']}</div>
            <div class='q-hint'>ℹ️ {q['hint']}</div>
        </div>
        """, unsafe_allow_html=True)

        prev_answer = st.session_state.answers.get(q["id"], None)
        yes_type = "primary" if prev_answer == "Yes" else "secondary"
        no_type  = "primary" if prev_answer == "No"  else "secondary"

        c1, c2 = st.columns(2)
        with c1:
            if st.button("✅  Yes", use_container_width=True, type=yes_type, key=f"yes_{q['id']}"):
                st.session_state.answers[q["id"]] = "Yes"
                go_to(st.session_state.page + 1)
                st.rerun()
        with c2:
            if st.button("❌  No", use_container_width=True, type=no_type, key=f"no_{q['id']}"):
                st.session_state.answers[q["id"]] = "No"
                go_to(st.session_state.page + 1)
                st.rerun()

        # Navigation row
        st.markdown("<br>", unsafe_allow_html=True)
        nav1, nav2 = st.columns([1, 1])
        with nav1:
            if st.session_state.page > 1:
                if st.button("← Back", use_container_width=True):
                    go_to(st.session_state.page - 1)
                    st.rerun()
        with nav2:
            if q["id"] in st.session_state.answers:
                if st.button("Skip →", use_container_width=True):
                    go_to(st.session_state.page + 1)
                    st.rerun()

# ══════════════════════════════════════════════════════════════════════════════
# RESULTS PAGE  (page == 21)
# ══════════════════════════════════════════════════════════════════════════════
elif st.session_state.page == 21:
    answers = st.session_state.answers
    yes_count = sum(1 for v in answers.values() if v == "Yes")
    total_answered = len(answers)

    # Weighted score (high-weight items count more)
    weighted = sum(
        q["weight"] for q in QUESTIONS
        if answers.get(q["id"]) == "Yes"
    )

    label, color, icon, advice = classify(yes_count, weighted)

    st.markdown(f"""
    <div style='text-align:center; padding: 1.5rem 0 0.5rem;'>
        <h1>📊 Your Results</h1>
        <p style='color:#6c757d;'>Based on {total_answered} answered questions</p>
    </div>
    """, unsafe_allow_html=True)

    col1, col2, col3 = st.columns([1, 5, 1])
    with col2:
        # Score circle
        st.markdown(f"""
        <div class='bat-card' style='text-align:center;'>
            <div class='score-circle' style='background:linear-gradient(135deg,{color}22,{color}44); border:3px solid {color};'>
                <div class='score-num' style='color:{color};'>{yes_count}</div>
                <div class='score-denom'>/ {total_answered}</div>
            </div>
            <div class='result-badge' style='background:{color}18; color:{color};'>
                {icon} &nbsp; {label}
            </div>
            <p style='color:#555; font-size:0.95rem; margin-top:0.5rem;'>{advice}</p>
        </div>
        """, unsafe_allow_html=True)

        # Weighted score info
        st.markdown(f"""
        <div style='background:#f8f9fa; border-radius:12px; padding:0.9rem 1.2rem; margin-bottom:1.2rem;
                    display:flex; justify-content:space-between; align-items:center;'>
            <span style='color:#6c757d; font-size:0.9rem;'>Weighted Symptom Score</span>
            <strong style='font-size:1.1rem; color:{color};'>{weighted}</strong>
        </div>
        """, unsafe_allow_html=True)

        # Detailed answer review
        st.markdown("### 📝 Answer Summary")
        rows_html = ""
        for q in QUESTIONS:
            ans = answers.get(q["id"], "—")
            dot_class = "dot-yes" if ans == "Yes" else "dot-no"
            symbol = "●" if ans != "—" else "○"
            color_dot = "#dc3545" if ans == "Yes" else "#198754"
            rows_html += f"""
            <div class='result-row'>
                <span style='min-width:1.6rem; font-size:0.8rem; color:#aaa;'>Q{q['id']}</span>
                <span style='flex:1; color:#333;'>{q['text']}</span>
                <span style='min-width:3.5rem; text-align:right; font-weight:600; color:{color_dot};'>{ans}</span>
            </div>"""
        st.markdown(f"<div class='bat-card' style='padding:1.5rem;'>{rows_html}</div>",
                    unsafe_allow_html=True)

        # Category breakdown
        st.markdown("### 🗂️ Positive Symptoms by Category")
        positive_cats = [q["category"] for q in QUESTIONS if answers.get(q["id"]) == "Yes"]
        if positive_cats:
            cat_html = "".join(
                f"<span style='background:#dc354518; color:#dc3545; border-radius:20px; "
                f"padding:0.3rem 0.85rem; margin:0.2rem; display:inline-block; font-size:0.88rem;'>"
                f"🔴 {c}</span>"
                for c in positive_cats
            )
            st.markdown(f"<div style='line-height:2;'>{cat_html}</div>", unsafe_allow_html=True)
        else:
            st.success("No positive bleeding symptoms reported.")

        # Disclaimer
        st.markdown("""
        <div class='disclaimer'>
            ⚠️ <strong>Medical Disclaimer:</strong> This tool is for educational and screening purposes only.
            It does not constitute a medical diagnosis. Please consult a qualified haematologist or physician
            for clinical evaluation and appropriate testing.
        </div>
        """, unsafe_allow_html=True)

        st.markdown("<br>", unsafe_allow_html=True)
        if st.button("🔄  Retake Assessment", use_container_width=True, type="primary"):
            st.session_state.answers = {}
            go_to(0)
            st.rerun()